<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Lib_Negocio\Lib_Negocio.csproj" />
	  <ProjectReference Include="..\Lib_Presentaciones\Lib_Presentaciones.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Pages\Emergentes\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="QuestPDF" Version="2026.5.0" />
	</ItemGroup>



</Project>
